package com.kwon.taboo.enums

enum class PayLoad {
    SELECTION_CHANGED,
    NUMBERING_VISIBILITY_CHANGED,
    ICON_VISIBILITY_CHANGED,
    TAB_FONT_FAMILY_CHANGED,
    TAB_COLOR_CHANGED,
    BALL_COLOR_CHANGED,
    TEXT_GRAVITY_CHANGED,
    ITEM_HEIGHT_CHANGED,
}